version: 1
preferences:
  language: "Japanese"

rules:
  - "会話、計画書(plan)、タスクリスト(task)などの内部ドキュメントは日本語で記述してください。"
  - "公開するコードのコメント、README、ドキュメント(コードベースに含まれるもの)は英語で記述してください。"
  - "コードの変更は最小限に留め、変更理由を明確にしてください。"
  - "不明確な点は推測せずに質問してください。"
  - "可読性向上のため、全角括弧は使用せず、半角括弧を使用してください。"
