version: 2
preferences:
  language: "English"

rules:
  - "Internal communications (chat, plans, tasks) and intermediate artifacts (e.g., .work/progress_*.md) should be written in the language specified in the user configuration (config.yml)."
  - "Public code comments, READMEs, and documentation (included in the codebase) must be written in English."
  - "Keep code changes minimal and clearly state the reason for the changes."
  - "Do not make assumptions about unclear points, ask questions instead."
  - "For better readability, use half-width parentheses instead of full-width parentheses."
  - "The .work directory is git-ignored. If writing to this directory is required, create or edit files via run_command instead of standard tools. Note that this method is permitted ONLY for the .work directory."
